### ISSUE TITLE
The mod does not work

### ISSUE THREAD

**Issue by BaKkur0** [Fourmisain/PerfectAccuracy#2]
Hello, I play on version 1.20.1 of factories, installed the mod version 1.2. It was written that it can work on both 1.19 and 1.20.1, but after checking it, nothing worked. I was playing solo and shooting from an ordinary bow with ordinary arrows. If you know how to fix it, then write to me, okay?

**Comment by Fourmisain** [comment]
What is "factories"? Is this some modpack?
If so, I need to know which one specifically. Can you send me a link to the CurseForge page?

Other than that, are you sure you are using the Fabric mod loader, not Forge? Because this mod only works with Fabric.

**Comment by BaKkur0** [comment]
> Что такое "фабрики"? Это какой-то модпак? Если да, то мне нужно знать, какой конкретно. Не могли бы вы прислать мне ссылку на страницу CurseForge?
> 
> Кроме этого, вы уверены, что используете загрузчик модов Fabric, а не Forge? Потому что этот мод работает только с Fabric.
> 
> редактировать: Кроме того, что именно вы подразумеваете под "ничего не сработало"? Например, как вы тестировали мод? Я не уверен, может быть, вы просто неправильно поняли, что делает мод.

**Comment by BaKkur0** [comment]
I meant fabric, I use a translator and made a mistake. I tested the mod like this: I aimed for a black spot near a birch tree, because I was in a birch grove. Aimed the bow at the spot, the cursor was exactly on it, shot from a length of about 10 blocks. But I didn't hit a black spot, but as without the mod, my arrow dropped a little.

**Comment by Fourmisain** [comment]
Ah, you're misunderstanding what the mod does.
This mod does not make arrows go straight.
It removes the variance between multiple shots.

So if you shoot multiple arrows from the same place and angle, it will land at the exact same spot.

Here, let me demonstrate:
https://github.com/Fourmisain/PerfectAccuracy/assets/8464472/96c3b6d7-d34b-4d4a-a044-6eecd67bc72a

All 5 arrows landed on the exact same spot. In Vanilla, they would be all over the place.

**Comment by BaKkur0** [comment]
Aah, that's it. Okay, thanks for explaining
